Bookshop/ViewModels/ShoppingCartViewModel.cs
using Bookshop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookshop.ViewModels
{
    public class ShoppingCartViewModel
    {
        public ShoppingCart ShoppingCart { get; set; }
        public int ShoppingCartTotal { get; set; }
    }
}

Bookshop/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bookshop.Data.Interfaces;
using Bookshop.Data.Models;
using Bookshop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Bookshop.Controllers
{
    public class BookController : Controller
    {
        IBookRepository _bookRepository;
        ICategoryRepository _categoryRepository;
        public BookController(ICategoryRepository categoryRepository,IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
            _categoryRepository = categoryRepository;
        }
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Book> books;

            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                books = _bookRepository.Books.OrderBy(n => n.BookId);
                currentCategory = "All books";
            }
            else
            {
                if (string.Equals("Science-Fiction", _category, StringComparison.OrdinalIgnoreCase))
                {
                    books = _bookRepository.Books.Where(p => p.Category.CategoryName.Equals("Science-Fiction")).OrderBy(n => n.BookId);
                }
                else
                {
                    books = _bookRepository.Books.Where(p => p.Category.CategoryName.Equals("Comics")).OrderBy(n => n.BookId);
                }
                currentCategory = _category;
            }


            var bookListViewModel = new BookListViewModel
            {
                Books = books,
                CurrentCategory = currentCategory
            };

            return View(bookListViewModel);
        }

        public ViewResult Search(string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Book> books;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                books = _bookRepository.Books.OrderBy(p => p.BookId);
            }
            else
            {
                books = _bookRepository.Books.Where(p => p.Name.ToLower().Contains(_searchString.ToLower()));
            }

            return View("~/Views/Book/List.cshtml", new BookListViewModel { Books = books, CurrentCategory = "All books" });
        }
    }
}

Bookshop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bookshop.Data.Interfaces;
using Bookshop.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bookshop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;

        public OrderController(IOrderRepository orderRepository, ShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }

        [Authorize]
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your card is empty,add some drinks first");
            }

            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete");
            }
            return View(order);
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Rahmat za pokupku!";
            return View();
        }
    }
}

Bookshop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bookshop.Data.Interfaces;
using Bookshop.Data.Models;
using Bookshop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bookshop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly ShoppingCart _shoppingCart;
        public ShoppingCartController(IBookRepository bookRepository,ShoppingCart shoppingCart)
        {
            _bookRepository = bookRepository;
            _shoppingCart = shoppingCart;
        }


        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            //foreach (var item in items)
            //    System.Diagnostics.Debug.WriteLine("sometext"+item.Drink.Name);
            _shoppingCart.ShoppingCartItems = items;

            var sCVM = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(sCVM);
        }
        [Authorize]
        public RedirectToActionResult AddToShoppingCart(int bookId)
        {
            var selectedBook = _bookRepository.Books.FirstOrDefault(p => p.BookId == bookId);
            if (selectedBook != null && selectedBook.InStock>0)
            {
                _shoppingCart.AddToCart(selectedBook, 1);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int BookId)
        {
            var selectedBook = _bookRepository.Books.FirstOrDefault(p => p.BookId == BookId);
            if (selectedBook != null)
            {
                _shoppingCart.RemoveFromCart(selectedBook);
            }

            return RedirectToAction("Index");
        }
    }
}

Bookshop/Views/ShoppingCart/Index.cshtml
    @model ShoppingCartViewModel

    <div class="row checkoutForm">
        <h2>Your shopping cart</h2>
        <h4>Here are the books in your shopping cart.</h4>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Selected amount</th>
                    <th>Book</th>
                    <th class="text-right">Author</th>
                    <th class="text-right">Pages</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
                {
                    <tr>
                        <td class="text-center">@line.Amount</td>
                        <td class="text-left">@line.Book.Name</td>
                        <td class="text-right">@line.Book.Author</td>
                        <td class="text-right">@line.Book.Pages </td>
                        <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-bookId="@line.Book.BookId"></a></td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">Total:</td>
                    <td class="text-right">
                        @Model.ShoppingCartTotal
                    </td>
                </tr>
            </tfoot>
        </table>

        <div class="text-right">
            <div class="btn-group ">
                <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
                <a class="btn-group">
                    <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        Add more books<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a asp-controller="Book" asp-action="List" asp-route-category="Science-Fiction">Science-Fiction</a></li>
                        <li><a asp-controller="Book" asp-action="List" asp-route-category="Comics">Comics</a></li>
                    </ul>
                </a>
            </div>
        </div>
    </div>